#ifndef TEA_CONSTANTS_HPP_INCLUDED
#define TEA_CONSTANTS_HPP_INCLUDED
#define TEA_NUMBER_OF_OPERATOR_GROUPS 6
#define TEA_VERSION "0.0.0"

// Tea keyword enumeration for indexing g_teakeywords (defined in main.cpp)
enum TEA_KEYWORDS
{
    TEA_KEYWORD_ASSIGN,
    TEA_KEYWORD_CALL,
    TEA_KEYWORD_DELETE,
    TEA_KEYWORD_ELIF,
    TEA_KEYWORD_ELSE,
    TEA_KEYWORD_EMPLACE,
    TEA_KEYWORD_END,
    TEA_KEYWORD_EXIT,
    TEA_KEYWORD_FLOAT,
    TEA_KEYWORD_IF,
    TEA_KEYWORD_IMPORT,
    TEA_KEYWORD_INCLUDE,
    TEA_KEYWORD_INT,
    TEA_KEYWORD_SNIPPET,
    TEA_KEYWORD_STRING,
    TEA_KEYWORD_SYSTEM,
    TEA_KEYWORD_WHILE,
    TEA_NUMBER_OF_KEYWORDS
};

#endif
